name: GladOS actions
on:
  push: 
    branches:
      - main

env:
  MIRROR_URL: git@github.com:EpitechPromo2027/B-FUN-500-NCY-5-1-glados-julian.bottiglione.git
  SELF_TARGET_BRANCH: release

defaults:
  run:
    shell: bash


jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
  
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: my-coding-style-checker
        run: |
          check.sh $(pwd) $(pwd)
          file="coding-style-reports.log"
          if [  $(wc -c $file | awk '{print $1}') == 0 ]
          then
            exit 0
          fi
          while read -r line
          do
            echo "::error::$line"
          done < "$file"
          exit 84

  check_program_compilation:
    runs-on: ubuntu-latest
    container: 
      image: epitechcontent/epitest-docker

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./.check_compilation.sh
        timeout-minutes: 5
  
  run_tests:
    runs-on: ubuntu-latest
    container:
      image:  epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - run: ./run_tests.sh
        timeout-minutes: 2

  push_to_mirror:
    runs-on: ubuntu-latest
    container:
      image:  epitechcontent/epitest-docker
    needs: 
      -  run_tests
      -  check_program_compilation
      -  check_coding_style
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: pixta-dev/repository-mirroring-action@v1
      - name: mirror to epitech repo
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.SSH_KEY }}

  push_to_relese_branch:
    needs:
      -  run_tests
      -  check_program_compilation
      -  check_coding_style
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
        - uses: actions/checkout@v4
        - name: push to release
          run: |
            rm .github/workflows/*
            git checkout -b ${{ env.SELF_TARGET_BRANCH }}
            git merge dev --no-commit --no-ff
            git reset HEAD .github/workflows/
            git push origin ${{ env.SELF_TARGET_BRANCH }}

