name: "Create Release"
on:
  push:

env:
  PROJECT_FOLDER: test
  RELEASE_NAME: interpretor

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Get the latest tag
      - name: Get date
        id: get_tag
        run: |
          date_abr=$(date +"%g%m%d-%H%M")
          echo "::set-output date::$date_abr"

      # Bump the version

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.bump_version.outputs.date_abr }}
          release_name: Release ${{ steps.bump_version.outputs.date_abr }}
          body: |
            Automatically created release for Interpretor.
          draft: false
          prerelease: false
