name: GladOS actions
on:
  push: 
    branches:
      - ${{ env.CURRENT_BRANCH }}

env:
  ACTION_FILE: .github/workflows/interpretor-mirroring.yml
  MIRROR_URL: git@github.com:EpitechPromo2027/B-FUN-500-NCY-5-1-glados-julian.bottiglione.git
  TARGET_BRANCH: interpretor-release
  CURRENT_BRANCH: Interpretor

defaults:
  run:
    shell: bash

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      image:  epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        timeout-minutes: 5
      - run: |
          cd glados
          stack build
          stack test

  mirror:
    runs-on: ubuntu-latest
    needs:
      -  run_tests
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched
      - name: Ssh -> Sparse Checkout -> Push
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_KEY }}" > ~/.ssh/github_actions
            chmod 600 ~/.ssh/github_actions
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
            ssh-add ~/.ssh/github_actions

            git remote add origin-destination ${{ env.MIRROR_URL }}
            git remote add origin-source ${{ github.repositoryUrl }}
            git checkout 

            git rm ${{ env.ACTION_FILE }}
            git config --global user.name "${{ github.actor }}"
            git commit --amend -m "${{ github.event.head_commit.message }}"
            git push --force --set-upstream origin-destination ${{ env.TARGET_BRANCH }}
