name: "Create Release"
on:
  push:
    branches:
      - Virtual-Machine-Release

env:
  RELEASE_NAME: RU-VIRTUAL-MACHINE
  BINARY_NAME: glados-virtual-machine-exe
  BINARY_RELEASE_NAME: ruvm

jobs:
  get_date:
    runs-on: ubuntu-latest
    outputs:
      date_abr: ${{ steps.getdate.outputs.date_abr }}
    steps:
      - name: Get Date
        id: getdate
        run: |
          date_abr=$(date +"%F-%H%M")
          echo "date_abr=${date_abr}" >> $GITHUB_OUTPUT
  create_release:
    runs-on: ubuntu-latest
    needs: get_date
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build binary
        #second and third command installs stack
        run: |
          sudo apt-get update -y
          sudo apt-get install -y make build-essential curl libffi-dev libffi8 libgmp-dev libgmp10 libncurses-dev libncurses5 libtinfo5 --fix-missing
          sudo apt-get install -y zlib1g-dev netbase
          curl -sSL https://get.haskellstack.org/ | sudo sh
          curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sudo sh
          make re
          if [ -x ${{ env.BINARY_NAME }} ]; then echo "Binary was built succesfully."; else echo "${{ env.BINARY_NAME }} was not found..." && exit 84 ; fi
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.get_date.outputs.date_abr }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.RELEASE_NAME }}-${{ env.VERSION }}
          body: |
            Working release of the RU virtual machine.
          draft: false
          prerelease: false
          
      - name: Upload Release Asset (Binary)
        id: upload-release-asset-bin
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: "./${{ env.BINARY_NAME }}"
          asset_name: ${{ env.BINARY_RELEASE_NAME }}
          asset_content_type: application/exe

      - name: Upload Release Asset (Doc)
        id: upload-release-asset-doc
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: "./developer_doc/"
          asset_name: "developer_doc/"
          asset_content_type: application/folder


  #create_release:
  #  runs-on: ubuntu-latest
  #  needs: get_date
  #  steps:
  #    - name: create-release
  #      env:
  #        VERSION: ${{ needs.get_date.outputs.date_abr }}
  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
  #      uses: actions/create-release@v1.1.4
  #      with:
  #        tag_name: ${{ env.VERSION }}
  #        release_name: Release ${{ env.VERSION }}
  #        body: |
  #          Automatically created release for Interpretor.
  #        draft: false
  #        prerelease: false
