version: '3.8'
services:
  angular-app:
    image: node:18
    container_name: angular-app
    working_dir: /usr/src/app
    volumes:
      - ./angular-app:/usr/src/app
    command: bash -c "npm install && npm run start -- --host 0.0.0.0"
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - express-api

  express-api:
    image: node:18
    container_name: express-api
    working_dir: /usr/src/app
    volumes:
      - ./express-api:/usr/src/app
    command: bash -c "npm install && npm run dev"
    ports:
      - "3000:3000"
